### ISSUE TITLE
Tap not working

### ISSUE THREAD

**Issue by cbrnr** [schloegl/homebrew-biosig#2]
Adding the tap does not work on my machine (Mac OS X 10.11.6):

```
$ brew tap schloegl/biosig
==> Tapping schloegl/biosig
Cloning into '/usr/local/Library/Taps/schloegl/homebrew-biosig'...
remote: Counting objects: 11, done.
remote: Compressing objects: 100% (11/11), done.
remote: Total 11 (delta 6), reused 3 (delta 0), pack-reused 0
Unpacking objects: 100% (11/11), done.
Checking connectivity... done.
Warning: Calling Formula.sha1 is deprecated!
Use Formula.sha256 instead.
/usr/local/Library/Taps/schloegl/homebrew-biosig/sigviewer.rb:9:in `<class:Stimfit>'
Please report this to the schloegl/biosig tap!

Warning: Calling SoftwareSpec#sha1 is deprecated!
Use SoftwareSpec#sha256 instead.
/usr/local/Library/Taps/schloegl/homebrew-biosig/sigviewer.rb:9:in `<class:Stimfit>'
Please report this to the schloegl/biosig tap!

Warning: Calling Resource#sha1 is deprecated!
Use Resource#sha256 instead.
/usr/local/Library/Taps/schloegl/homebrew-biosig/sigviewer.rb:9:in `<class:Stimfit>'
Please report this to the schloegl/biosig tap!

Error: Invalid formula: /usr/local/Library/Taps/schloegl/homebrew-biosig/sigviewer.rb
No available formula with the name "sigviewer" 
In formula file: /usr/local/Library/Taps/schloegl/homebrew-biosig/sigviewer.rb
Expected to find class Sigviewer, but only found: Stimfit.
Error: Cannot tap schloegl/biosig: invalid syntax in tap!
```

**Comment by schloegl** [comment]
brew tap schloegl/biosig 
    is now fixed.

**Comment by cbrnr** [comment]
Nice, thanks @schloegl, tapping is now working. However, building libbiosig results in an error. This is already described in #1.
